# Known issues:
# Hive LLAP will not start on small machines
# NiFi moved to 9092 to avoid a port clash when everything is on one node

desc: Multiple node cluster including HDP-3.0.1 & HDF-3.3
deploywait: 1800
purge: true
priority: 
seq:
- prep_deps: [druid_llap, druidllap]
- prep_spec: [druid_llap, druidllap]
- do_builds: [druidllap]
- open_port: [-1, 1, 65534, '0.0.0.0/0']
- open_port: [tcp, 8080, 8080, '0.0.0.0/0']
input:
  yarn.vcores: 16
  yarn.capacity: 60000
  enable_hive_interactive: true
blueprint:
  name: blueprint.json
recipe:
- name: airline_data.sh
  typ: PRE_AMBARI_START
- name: druid_metastore_install.sh
  typ: POST_CLUSTER_INSTALL
group:
  master:
    recipe: [airline_data]
    machine: 14x60-18x68
    type: GATEWAY
    nodes: 1
  druid_broker:
    recipe: [druid_metastore_install]
    machine: 14x60-18x68
    type: CORE
    nodes: 1
  druid_historical:
    machine: 14x60-18x68
    type: CORE
    nodes: 1
  druid_middlemanager:
    machine: 14x60-18x68
    type: CORE
    nodes: 1
  druid_overlord_coordinator:
    machine: 14x60-18x68
    type: CORE
    nodes: 1
  compute_node:
    machine: 14x60-18x68
    type: CORE
    nodes: 3